language: python
python:
  - "2.7"
install:
  - git clone https://github.com/evennia/evennia.git
  - cd evennia
  - pip install -e .
  - cd ..
  - pip install wiki
  - cd $TRAVIS_BUILD_DIR
script:
  - evennia migrate
  - evennia --settings settings.py test evennia
  - evennia test
